# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "example/simple_kiosk_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/kiosk_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/tekartik_kiosk"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/tekartik_kiosk/example"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "packages/tk_adb_app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - autosubmit
