name: _
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - example/simple_kiosk_app
  - packages/kiosk_app
  - packages/kiosk
  - packages/kiosk/example
  - packages/tk_adb_app
  - packages/web_kiosk_app
