# This is a basic workflow to help you get started with Actions

name: Run CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 21 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      # Access to private repo
    # - uses: webfactory/ssh-agent@v0.8.0
    #  with:
    #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: dart --version
    - run: flutter --version
    - run: dart pub global activate dev_build
    - run: dart pub global run dev_build:run_ci --recursive
